## YAML Template

server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: true
      routes:
      - id: votify-user
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1/user/**
      - id: node-auth
        uri: http://localhost:3000
        predicates:
          - Path=/auth/google/**
      - id: node-election-service
        uri: http://localhost:3001
        predicates:
          - Path=/api/election-service/**
      - id: node-buzon-service
        uri: http://localhost:3002
        predicates:
          - Path=/api/buzon-service/**